# GPIO Pin assignments
PIN_LED_RED = 13
PIN_LED_GREEN = 19
PIN_LED_BLUE = 26
PIN_MOTION = 17
PIN_DISTANCE_ECHO = 21
PIN_DISTANCE_TRIGGER = 20
PIN_DHT11 = 4
PIN_BUZZER = 27

# Distance thresholds 
DISTANCE_RED_THRESHOLD = 10
DISTANCE_YELLOW_MAX = 30

# Timing
DEFAULT_FREQUENCY = 1.0  
FREQUENCY_STEP = 0.1  
BUZZER_DURATION = 0.5 

# GUI Settings
BUTTON_WIDTH = 16
BUTTON_HEIGHT = 3
BUTTON_PADDING = 8
BUTTON_BORDER_WIDTH = 4
BUTTON_WRAP_LENGTH = 75